server:
  port: 0

spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/analyzer?currentSchema=orders
    username: postgres
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        default_schema: orders

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
