spring:
  main:
    web-application-type: none
  kafka:
    bootstrap-servers: localhost:9092
  datasource:
    url: jdbc:postgresql://localhost:5433/analyzer
    username: postgres
    password: password
  jpa:
    hibernate:
      ddl-auto: none
  sql:
    init:
      mode: always

grpc:
  client:
    hub-router:
      address: 'discovery:///hub-router'
      enableKeepAlive: true
      keepAliveWithoutCalls: true
      negotiationType: plaintext

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
